# Generated by Django 6.0.5 on 2026-05-24 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'examination_classinfo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='考试描述')),
                ('exam_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='考试码')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('class_specific', '指定班级')], default='public', max_length=20, verbose_name='可见性')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=60, verbose_name='时长(分钟)')),
                ('total_score', models.IntegerField(default=100, verbose_name='满分')),
                ('require_qr', models.BooleanField(default=False, verbose_name='需扫码')),
                ('submission_method', models.CharField(choices=[('manual', '手动提交'), ('auto', '自动提交')], default='manual', max_length=10, verbose_name='提交方式')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='题目乱序')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='选项乱序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('allowed_classes', models.ManyToManyField(blank=True, related_name='exams', to='examination.classinfo', verbose_name='可见班级')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'examination_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('blank', '填空题')], max_length=10, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题干')),
                ('options', models.TextField(blank=True, default='[]', verbose_name='选项(JSON)')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('score', models.IntegerField(default=10, verbose_name='分值')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='解析')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examination.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'examination_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(blank=True, default='{}', verbose_name='答案(JSON)')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('grading_details', models.TextField(blank=True, default='{}', verbose_name='判题详情(JSON)')),
                ('is_graded', models.BooleanField(default=False, verbose_name='已判题')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('submission_method', models.CharField(choices=[('manual', '手动提交'), ('auto', '自动提交')], default='manual', max_length=10, verbose_name='提交方式')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='答题IP')),
                ('status', models.CharField(choices=[('draft', '答题中'), ('submitted', '已提交'), ('auto_graded', '自动判分完成'), ('manual_grading', '人工阅卷中'), ('manual_graded', '人工判分完成'), ('reviewed', '已复核')], default='draft', max_length=20, verbose_name='状态')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='examination.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'examination_exam_record',
                'ordering': ['-start_time'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='examination.exam', verbose_name='考试')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='examination.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '考试题目',
                'verbose_name_plural': '考试题目',
                'db_table': 'examination_exam_question',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StudentClassRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to='examination.classinfo', verbose_name='班级')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_relations', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生班级关系',
                'verbose_name_plural': '学生班级关系',
                'db_table': 'examination_student_class_relation',
                'unique_together': {('student', 'class_info')},
            },
        ),
    ]
