# Generated by Django 6.0.5 on 2026-05-24 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('screen_switch', '切屏'), ('copy', '复制'), ('paste', '粘贴'), ('focus_loss', '失去焦点'), ('tab_switch', '切换标签页')], max_length=20, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='examination.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'examination_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('exam_created', '考试创建'), ('exam_started', '考试开始'), ('exam_ended', '考试结束'), ('score_released', '成绩发布'), ('system', '系统通知')], default='system', max_length=20, verbose_name='通知类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='examination.exam', verbose_name='相关考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'examination_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
