# Generated by Django 4.2.11 on 2026-03-27 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='考试名称')),
                ('description', models.TextField(blank=True, verbose_name='考试描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('max_score', models.IntegerField(default=100, verbose_name='满分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('blank', '填空题')], max_length=10, verbose_name='题型')),
                ('question_text', models.TextField(verbose_name='题干')),
                ('option_a', models.CharField(blank=True, max_length=200, verbose_name='选项 A')),
                ('option_b', models.CharField(blank=True, max_length=200, verbose_name='选项 B')),
                ('option_c', models.CharField(blank=True, max_length=200, verbose_name='选项 C')),
                ('option_d', models.CharField(blank=True, max_length=200, verbose_name='选项 D')),
                ('answer', models.CharField(max_length=100, verbose_name='正确答案')),
                ('score', models.IntegerField(default=5, verbose_name='分值')),
                ('order', models.IntegerField(default=0, verbose_name='题目顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['exam', 'order'], name='exams_quest_exam_id_4ac027_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sheet', models.JSONField(blank=True, default=dict, verbose_name='答题草稿')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='最终得分')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否交卷')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exams.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_submitted'], name='exams_examr_student_b5ffff_idx'), models.Index(fields=['exam', 'is_submitted'], name='exams_examr_exam_id_4099a8_idx')],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='exams_exam_created_66bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'end_time'], name='exams_exam_start_t_495a08_idx'),
        ),
    ]
