# Generated by Django 4.2.11 on 2026-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='grading_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='判题详情'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='submission_method',
            field=models.CharField(choices=[('manual', '手动提交'), ('auto', '自动提交')], default='manual', max_length=10, verbose_name='提交方式'),
        ),
    ]
