# Generated by Django 4.2.11 on 2026-04-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_question_exam_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=5, verbose_name='默认分值'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='exams_examq_exam_id_b093bd_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['question'], name='exams_examq_questio_a67420_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by', '-created_at'], name='exams_quest_created_683f0f_idx'),
        ),
    ]
