# Generated by Django 4.2.11 on 2026-04-03 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0006_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, verbose_name='班级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='visibility',
            field=models.CharField(choices=[('public', '全局可见'), ('class_specific', '指定班级可见')], default='class_specific', max_length=20, verbose_name='可见性'),
        ),
        migrations.AddField(
            model_name='exam',
            name='allowed_classes',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exams.classinfo', verbose_name='允许访问的班级'),
        ),
        migrations.CreateModel(
            name='StudentClassRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.classinfo', verbose_name='班级')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_relations', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生班级关联',
                'verbose_name_plural': '学生班级关联',
                'indexes': [models.Index(fields=['student'], name='exams_stude_student_3e3fc4_idx'), models.Index(fields=['class_info'], name='exams_stude_class_i_24ee33_idx')],
                'unique_together': {('student', 'class_info')},
            },
        ),
        migrations.AddIndex(
            model_name='classinfo',
            index=models.Index(fields=['teacher', '-created_at'], name='exams_class_teacher_bce2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='classinfo',
            index=models.Index(fields=['name'], name='exams_class_name_878782_idx'),
        ),
    ]
