# Generated by Django 4.2.11 on 2026-04-03 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_classinfo_exam_visibility_exam_allowed_classes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classinfo',
            unique_together={('teacher', 'name')},
        ),
    ]
